# ==============================
# General Settings
# ==============================
spring.application.name=base-project
server.port=8080
server.forward-headers-strategy=framework

# ==============================
# Application Information
#   - information extracted from the POM (to be used as you wish)
# ==============================
application.info.name=@project.name@
application.info.description=@project.description@
application.info.app-version=@project.version@
application.info.java-version=@java.version@

# ==============================
# Jackson Settings
#   - throws exception if there are fields not expected by the resource/api
#   - throws exception if fields exist but are @JsonIgnore
# ==============================
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

# ==============================
# SpringDoc Settings
#   - http://localhost:8080/swagger-ui/index.html
#   - http://localhost:8080/v3/api-docs
# ==============================
springdoc.api-docs.version=openapi_3_1
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
